const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "+94705215918"
const SESSION_ID = "PRABATH-MD~AzdSRYCR#hEQ98TRxqjBfN10OalsNWJQMx0bRwYdF3N3hWcESu-I"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
